default: &default
   adapter: postgresql
   encoding: unicode
  
development:
   adapter: postgresql
   encoding: unicode
   database: librarydb
   username: rubyuser
   password: ruby1

test:
   adapter: postgresql
   encoding: unicode
   database: librarydb
   username: rubyuser
   password: ruby1
 
production:
   adapter: postgresql
   encoding: unicode
   database: librarydb
   username: rubyuser
   password: ruby1